In [1]:
import pandas as pd
import numpy as np

In [2]:
transactions = pd.read_csv("customer_transactions_contaminated.csv")

In [3]:
transactions.head()

,CustomerID,TransactionID,TransactionDate,Amount,ProductCategory,PaymentMethod
0,60567026-f719-4cd6-849e-137e86d8938f,5ff75116-0a50-4d04-80fb-31e5ccbb0769,2024-05-15,117.64,Clothing,PayPal
1,4090ba85-b111-4f75-a792-c777965f5255,2c39b9fe-ff57-4d39-9321-9f5cdf187aa1,2023-04-26,466.14,Health & Beauty,Bank Transfer
2,9223891b-73ff-4d5c-b8ae-13ece82ee28b,f79588dd-3db9-4ffa-97f8-7de0e64259f1,2022-09-23,563.99,Clothing,Debit Card
3,9243eebc-938f-480c-8564-16d503d250de,401c0fc9-60df-4455-ad78-67c132f9897d,2024-04-15,254.44,Automotive,PayPal
4,6e3e8eb8-bc0f-4ffe-9f74-5d5efec9502f,2034aebc-8280-4254-a667-92bcd1c2be4f,2024-06-03,590.52,Home & Garden,Bank Transfer

In [4]:
import pandas as pd
import numpy as np

In [5]:
transactions = pd.read_csv("customer_transactions_contaminated.csv")

In [6]:
transactions.shape

(3200, 6)

In [7]:
transactions.dtypes

CustomerID         str
TransactionID      str
TransactionDate    str
Amount             str
ProductCategory    str
PaymentMethod      str
dtype: object

In [8]:
transactions.isnull().sum()

CustomerID           0
TransactionID        0
TransactionDate      0
Amount             304
ProductCategory    299
PaymentMethod        0
dtype: int64

In [9]:
transactions.duplicated().sum()

np.int64(185)

In [10]:
transactions[transactions.duplicated(keep=False)].head(20)

,CustomerID,TransactionID,TransactionDate,Amount,ProductCategory,PaymentMethod
0,60567026-f719-4cd6-849e-137e86d8938f,5ff75116-0a50-4d04-80fb-31e5ccbb0769,2024-05-15,117.64,Clothing,PayPal
9,474f9233-0616-431b-b3e9-a6feabe68abb,f8bde21a-7a6b-41f6-ac39-eeb77640fa9b,2023-06-15,149.39,Clothing,Debit Card
16,54b3556e-e480-41a2-9dcd-7da1d91655aa,c181a599-fcc7-4f9b-b618-783684e0fd24,2023-03-06,861.39,Clothing,Bank Transfer
36,9560ed71-7a04-4cd9-a576-b622c5690487,ad529898-c1b5-4fe7-b30b-a9f19c666386,2024-05-31,833.48,Automotive,Bank Transfer
45,d3493edf-9847-46ef-b400-7063b54bcf63,6fa36483-8ac7-4af8-9cc7-e0607673f331,2022-07-15,119.65,Clothing,PayPal
65,a0db86bf-0c2d-4c9e-8d3b-f5b33ac37cee,1048e98c-90fd-4cef-ba62-eb4b16816596,2023-09-08,596.73,Clothing,Credit Card
84,978c4300-e302-4677-b7f0-7b4a8e2a87b8,9af33eb6-952d-4f50-b8af-cf570b517d83,2023-07-20,80.69,Health & Beauty,PayPal
136,262adfc3-44ae-442d-a213-2d3eb9e668a3,966703bc-1ed1-44f3-a868-d2f09973e857,2022-08-31,NaN,Home & Garden,Bank Transfer
151,8f61e984-4fa5-4941-95ee-e42c92758e02,957d522b-3074-415c-ad64-6fd800ddc286,2024-02-22,334.96,Electronics,PayPal
162,e6f38640-260c-4c82-bb98-1a5ad730365e,c496b5ff-a157-45ad-95c8-4935b0e1b4b8,2022-11-05,359.4,Automotive,Debit Card
178,e8a5fdb8-fcd9-450c-9635-e376266c8bcf,208e7d1b-e7da-46f8-b6b8-678eef27699e,2023-06-21,645.53,Automotive,PayPal
218,9e5a62bf-b2cc-4743-b266-252c16a36f83,97f0f226-6531-4acb-b5fc-a3bbcb591c17,2023-01-06,NaN,Health & Beauty,PayPal
236,83b8546f-50a6-4b60-8dfc-78004cc0076c,6a76ae87-3484-430f-9372-01c8f1498959,2024-01-06,168.66,Health & Beauty,Debit Card
244,8a1b714a-0592-42f9-bdc0-e7d67163f3f1,ab88e4c7-3bc3-4dd4-879c-db75b263171d,2024-01-31,978.11,Electronics,PayPal
278,6bc3aaad-57cc-4fae-b57f-18faa88ce95b,191af024-d4d3-4144-86f7-11e09e4e9df8,2023-02-14,185.97,NaN,Debit Card
282,b10dbfea-ac81-4cdf-be3c-62248bbd5838,02a36fd6-8d10-4179-8b84-f011e8551a64,2024-06-02,NaN,Health & Beauty,Debit Card
295,79fc606a-c02c-4c39-b065-3e88a59b366c,604d5342-6293-4870-997d-deeef832c557,2023-10-09,442.99,Home & Garden,PayPal
301,0865a620-9ff4-46ec-9f14-7efdd071a041,206e70f6-6775-4945-8e6e-cad206fe2a5f,2022-12-02,24.94,Clothing,Credit Card
305,634b25ce-d205-4a1e-b277-b70efc033fc6,ded7963e-87b2-45c2-ad06-359212a961e6,2024-01-25,726.69,Home & Garden,Credit Card
364,3d8408ab-60f2-465f-a112-d6b7747c4a4a,bfdef222-6989-42a9-8689-c43d017e9b55,2024-05-15,954.97,Automotive,PayPal

In [11]:
transactions_cleaned = transactions.drop_duplicates().copy()

In [12]:
transactions_cleaned.shape

(3015, 6)

In [13]:
transactions_cleaned["Amount"].value_counts(dropna=False).head(20)

Amount
NaN       283
-100       39
Free       30
0          29
54.66       2
175.31      2
628.86      2
368.91      2
129.92      2
185.97      2
634.41      2
372.45      2
404.53      2
390.81      2
457.83      2
347.7       2
999.86      2
724.64      2
50.07       2
508.4       2
Name: count, dtype: int64

In [14]:
transactions_cleaned["Amount"] = pd.to_numeric(
    transactions_cleaned["Amount"],
    errors="coerce"
)

In [15]:
transactions_cleaned["Amount"].dtype

dtype('float64')

In [16]:
transactions_cleaned[transactions_cleaned["Amount"] < 0]

,CustomerID,TransactionID,TransactionDate,Amount,ProductCategory,PaymentMethod
274,e6f4ae74-d58d-4770-8ebc-89c1f8778a6d,814d25d8-690b-45bb-96c9-b7a3e92a61db,2023-01-25,-100.0,NaN,PayPal
319,b91999f9-b7ed-4da4-a285-1dafae98e21d,fb908e24-4c1e-4e24-a1b0-62465fa0515c,2024-03-22,-100.0,Health & Beauty,Debit Card
334,a800ccba-e1ca-4f52-ad9f-14f3432699c9,487ecd9b-57c8-447c-a2a8-e55477ba0d6d,2023-09-25,-100.0,Clothing,Bank Transfer
381,a94e3f55-2f0e-432e-8706-9815c4371376,f53b16b4-d042-44ca-a073-4acdd546b519,2024-01-06,-100.0,Home & Garden,PayPal
447,ca645b4d-28a4-42ec-99a7-8000d38bf2e0,f35cadbe-6ae1-427d-8b41-5749cc1173e6,2023-06-18,-100.0,Electronics,Bank Transfer
449,a7c29c33-e968-4d84-82cd-1269ed1e7c1e,77954a26-9a04-4806-b525-7f33f554d255,2022-09-11,-100.0,Home & Garden,Credit Card
476,ac6b4d61-3d14-4362-b226-8c0c5786d6df,1074d2cf-a7d5-4ebd-baa9-4660b2df5ec8,2023-07-17,-100.0,Health & Beauty,Credit Card
500,ffe9a403-ac25-4aad-a809-ac9687ff3fcd,c59819cc-cf92-4929-ad22-ef3435187be9,2023-04-01,-100.0,Automotive,Bank Transfer
563,f05ec030-ac96-417d-a73c-e3ca3adc1a30,f39c8b1d-595a-4656-8108-25981bf3fa14,03/04/2023,-100.0,Electronics,Debit Card
652,f56e56b7-bbde-455c-b570-61cd2005b4e4,f99eba1f-0092-4487-b753-9fce61e0ca26,2023-02-05,-100.0,Automotive,PayPal
702,ab87ecef-f7ea-49b0-8c50-c31442ad5c46,64138a25-3a63-41fd-aa81-f74231597191,2022-12-04,-100.0,Home & Garden,Debit Card
727,db10c135-1080-4fce-b653-d5a5fb572fa8,adbe44db-78ec-408b-80ad-e119e0f58123,2024-05-13,-100.0,Home & Garden,Credit Card
1129,6b6cd86a-d0af-48ab-ada5-e596f726cffa,eed1a5a0-4a6b-40b1-9c43-abfeff1a7735,2024-06-02,-100.0,Clothing,Credit Card
1240,03fac2e6-f130-4cf6-b8b8-2f147c2fe60a,6f57c9c3-0c11-4d34-9392-08eb6b91fd0e,2024-05-21,-100.0,Home & Garden,Debit Card
1241,799943c7-3b71-4f24-9b16-c2fcaf9b3871,09b0508b-a705-48d0-8594-5b7d85d024eb,2022-11-08,-100.0,Automotive,PayPal
1263,38d746bd-c227-416a-aa28-610ffd379e58,db154379-42a3-4ae0-a4d3-29c53226f8a1,2024-06-22,-100.0,Electronics,Bank Transfer
1298,8375d38f-88e2-4c33-9647-f8b8b55b1426,f01412a4-6d1c-46ce-a912-7b0a8c2a7596,2023-02-23,-100.0,Health & Beauty,Bank Transfer
1577,7eb7f7df-9b0a-416a-829e-bcf4d8bd57dc,6cfe5871-8524-4d81-abaa-a54fdd3c873d,2023-06-11,-100.0,Automotive,PayPal
1705,f102f93b-f32c-41d3-adcc-25e02a67c34f,084e56a5-99eb-48df-801e-bda9cd5ff591,2023-11-03,-100.0,Electronics,PayPal
1808,28097c07-e810-4e64-8eae-bff2abd81bc1,ab723d41-abdc-412b-b3b9-68796b746a8e,2023-07-11,-100.0,Automotive,Credit Card
1907,b7b84b81-c61b-4f23-b3db-b18010484122,d7740397-087b-49bb-bf31-2a50ca0e70f6,2023-03-14,-100.0,Clothing,PayPal
1942,e7e5e8fe-5fdd-43e6-92e1-5ea3e399486e,5b6352cf-da83-46ab-a0ff-79da90691392,2023-12-25,-100.0,Electronics,PayPal
1994,d968cee0-3524-42d4-a0f7-5fe6e8284890,0705d2f0-ab60-4664-b65e-971e3e2c27d5,2023-10-09,-100.0,Clothing,Debit Card
2191,1f5c50db-9c55-4bbc-8a93-c7994a7bb3d3,4b4ddbb6-36cf-44eb-8e7a-b27c529f1cff,2022-12-20,-100.0,Automotive,Bank Transfer
2239,448245da-3a0b-4f52-a40f-a25ca0a2fb6b,ddebc095-ed7c-4c6e-87d8-e7f00c0b50c6,2023-01-24,-100.0,Home & Garden,Credit Card
2319,21098ed8-fac6-4727-8f0c-953365b6c837,c100f59f-61aa-4c82-825e-dedfde73917b,2023-02-14,-100.0,Home & Garden,PayPal
2443,ce3f403f-b955-4364-ae22-bf351381e01f,0e5b9cc6-9b94-45fc-8bf8-b8031cd987a7,2023-04-21,-100.0,Home & Garden,Bank Transfer
2467,0e678ba1-7b5f-46aa-8b5a-6dc1190373be,33ce68ea-42c4-48eb-8631-c8f611d2a330,2023-03-01,-100.0,Clothing,Debit Card
2480,eca27290-1c40-48c6-b0a5-8afedd9be099,341e25ef-3062-484d-8d07-cc4e0ddb996f,2022-08-02,-100.0,Clothing,Credit Card
2516,7e280186-770e-4c4a-b330-73dd471f956a,35faff4a-1bf8-4b42-a7ac-847b4970f4b8,2023-09-19,-100.0,Home & Garden,Bank Transfer
2522,bfe55c3b-668e-485d-9476-670acd50b12b,52bb2a8d-acab-45f9-9817-6e9fe7567824,2024-05-03,-100.0,Health & Beauty,Debit Card
2621,8d435ee0-fa33-4553-880a-e26511ac3921,c0d0ae2b-eb99-49e5-89ad-0624ad136056,2023-03-27,-100.0,Home & Garden,Bank Transfer
2737,c56a1423-e1b0-45c1-974a-55f5fa029c88,b401a1e8-6cc3-4ab6-bff4-c41a3847329a,2024-05-31,-100.0,Electronics,PayPal
2910,f35c6e3f-2fac-4b7a-b713-863a0a37160c,e2d7a068-e92e-407a-8d48-4cf8da4a4c2c,2024-03-12,-100.0,Health & Beauty,PayPal
3012,24b043e8-6fca-4d86-95a8-837e0ca09072,dc9453eb-3922-4a5f-91c0-ccb226ca91f7,2023-06-01,-100.0,Health & Beauty,Debit Card
3038,b94b3531-591d-445c-b282-dcacb0baca5b,27fb25aa-f148-423f-967c-4d1764e26b29,2024-04-18,-100.0,Automotive,Credit Card
3050,a9af986b-d677-421a-81df-3d289ce9e38f,5f93f1dc-0363-4e69-979b-f5d58fd42658,2023-09-30,-100.0,NaN,Bank Transfer
3073,e7cf6999-b4ec-4ce4-bb09-bfd18d61d933,2e0b66a9-af5d-4cf9-bb60-55ab2932edee,2023-05-10,-100.0,Electronics,Bank Transfer
3123,8de3d5b9-1f1a-4bd7-b242-6cb09d7f3609,5fca256b-cd5a-48fa-8b07-37f39adde8c9,2023-05-17,-100.0,Clothing,Bank Transfer
3177,3ea377e6-1156-457e-8b4e-71fa6663e6bf,c751a808-ed8d-44d0-8c52-8253ad564c9a,2023-09-22,-100.0,Health & Beauty,Credit Card

In [17]:
transactions_cleaned.loc[
    transactions_cleaned["Amount"] < 0,
    "Amount"
] = np.nan

In [18]:
transactions_cleaned["Amount"].isnull().sum()

np.int64(353)

In [19]:
transactions_cleaned["Amount"].median()

np.float64(504.14)

In [20]:
transactions_cleaned["Amount"] = transactions_cleaned["Amount"].fillna(504.14)

In [21]:
transactions_cleaned["Amount"].isnull().sum()

np.int64(0)

In [22]:
transactions_cleaned["ProductCategory"].value_counts(dropna=False)

ProductCategory
Clothing           571
Electronics        564
Automotive         540
Home & Garden      530
Health & Beauty    528
NaN                282
Name: count, dtype: int64

In [23]:
transactions_cleaned["ProductCategory"] = transactions_cleaned["ProductCategory"].fillna("Unknown")

In [24]:
transactions_cleaned["ProductCategory"].isnull().sum()

np.int64(0)

In [25]:
transactions_cleaned["TransactionDate"].value_counts().head(10)

TransactionDate
2022-10-31    11
2024-01-06    11
2023-05-28    10
2022-12-14    10
2023-04-06    10
2023-10-19    10
2023-05-17    10
2023-12-19    10
2022-09-23     9
2024-01-12     9
Name: count, dtype: int64

In [26]:
transactions_cleaned[
    transactions_cleaned["TransactionDate"].str.contains("/", na=False)
]["TransactionDate"].value_counts().head(20)

TransactionDate
30/05/2023    3
24/05/2023    2
12/06/2024    2
17/10/2023    2
27/03/2024    2
01/04/2024    1
13/12/2022    1
26/10/2022    1
25/02/2023    1
23/03/2023    1
16/09/2023    1
11/09/2023    1
28/10/2022    1
12/10/2023    1
13/04/2023    1
30/07/2022    1
29/12/2023    1
04/03/2023    1
06/07/2022    1
12/07/2023    1
Name: count, dtype: int64

In [27]:
transactions_cleaned["TransactionDate"] = pd.to_datetime(
    transactions_cleaned["TransactionDate"],
    format="mixed",
    dayfirst=True,
    errors="coerce"
)

In [28]:
transactions_cleaned["TransactionDate"].dtype

dtype('<M8[us]')

In [29]:
transactions_cleaned["TransactionDate"].isnull().sum()

np.int64(0)

In [30]:
print("FINAL DATASET CHECK")
print("-------------------")

print("\nDataset Shape:")
print(transactions_cleaned.shape)

print("\nData Types:")
print(transactions_cleaned.dtypes)

print("\nMissing Values:")
print(transactions_cleaned.isnull().sum())

print("\nDuplicate Rows:")
print(transactions_cleaned.duplicated().sum())

FINAL DATASET CHECK
-------------------

Dataset Shape:
(3015, 6)

Data Types:
CustomerID                    str
TransactionID                 str
TransactionDate    datetime64[us]
Amount                    float64
ProductCategory               str
PaymentMethod                 str
dtype: object

Missing Values:
CustomerID         0
TransactionID      0
TransactionDate    0
Amount             0
ProductCategory    0
PaymentMethod      0
dtype: int64

Duplicate Rows:
0

In [32]:
import pandas as pd
import numpy as np

transactions = pd.read_csv("customer_transactions_contaminated.csv")

transactions.head()

transactions.shape

transactions.dtypes

transactions.isnull().sum()

CustomerID           0
TransactionID        0
TransactionDate      0
Amount             304
ProductCategory    299
PaymentMethod        0
dtype: int64

In [33]:
transactions.duplicated().sum()

np.int64(185)

In [34]:
transactions_cleaned = transactions.drop_duplicates().copy()

In [35]:
transactions_cleaned.shape

(3015, 6)

In [36]:
transactions_cleaned["Amount"].value_counts(dropna=False).head(20)

Amount
NaN       283
-100       39
Free       30
0          29
54.66       2
175.31      2
628.86      2
368.91      2
129.92      2
185.97      2
634.41      2
372.45      2
404.53      2
390.81      2
457.83      2
347.7       2
999.86      2
724.64      2
50.07       2
508.4       2
Name: count, dtype: int64

In [37]:
transactions_cleaned["Amount"] = pd.to_numeric(
    transactions_cleaned["Amount"],
    errors="coerce"
)

In [38]:
transactions_cleaned["Amount"].dtype

dtype('float64')

In [39]:
transactions_cleaned.loc[
    transactions_cleaned["Amount"] < 0,
    "Amount"
] = np.nan

In [40]:
transactions_cleaned["Amount"].isnull().sum()

np.int64(353)

In [41]:
transactions_cleaned["Amount"].median()

np.float64(504.14)

In [42]:
transactions_cleaned["Amount"] = transactions_cleaned["Amount"].fillna(504.14)

In [43]:
transactions_cleaned["Amount"].isnull().sum()

np.int64(0)

In [44]:
transactions_cleaned["ProductCategory"].value_counts(dropna=False)

ProductCategory
Clothing           571
Electronics        564
Automotive         540
Home & Garden      530
Health & Beauty    528
NaN                282
Name: count, dtype: int64

In [45]:
transactions_cleaned["ProductCategory"] = transactions_cleaned["ProductCategory"].fillna("Unknown")

In [46]:
transactions_cleaned["ProductCategory"].isnull().sum()

np.int64(0)

In [47]:
transactions_cleaned["TransactionDate"].value_counts().head(10)

TransactionDate
2022-10-31    11
2024-01-06    11
2023-05-28    10
2022-12-14    10
2023-04-06    10
2023-10-19    10
2023-05-17    10
2023-12-19    10
2022-09-23     9
2024-01-12     9
Name: count, dtype: int64

In [48]:
transactions_cleaned[
    transactions_cleaned["TransactionDate"].str.contains("/", na=False)
]["TransactionDate"].value_counts().head(20)

TransactionDate
30/05/2023    3
24/05/2023    2
12/06/2024    2
17/10/2023    2
27/03/2024    2
01/04/2024    1
13/12/2022    1
26/10/2022    1
25/02/2023    1
23/03/2023    1
16/09/2023    1
11/09/2023    1
28/10/2022    1
12/10/2023    1
13/04/2023    1
30/07/2022    1
29/12/2023    1
04/03/2023    1
06/07/2022    1
12/07/2023    1
Name: count, dtype: int64

In [49]:
transactions_cleaned["TransactionDate"] = pd.to_datetime(
    transactions_cleaned["TransactionDate"],
    format="mixed",
    dayfirst=True,
    errors="coerce"
)

In [50]:
transactions_cleaned["TransactionDate"].dtype

dtype('<M8[us]')

In [51]:
transactions_cleaned["TransactionDate"].isnull().sum()

np.int64(0)

In [52]:
print("FINAL DATASET CHECK")
print("-------------------")

print("\nDataset Shape:")
print(transactions_cleaned.shape)

print("\nData Types:")
print(transactions_cleaned.dtypes)

print("\nMissing Values:")
print(transactions_cleaned.isnull().sum())

print("\nDuplicate Rows:")
print(transactions_cleaned.duplicated().sum())

FINAL DATASET CHECK
-------------------

Dataset Shape:
(3015, 6)

Data Types:
CustomerID                    str
TransactionID                 str
TransactionDate    datetime64[us]
Amount                    float64
ProductCategory               str
PaymentMethod                 str
dtype: object

Missing Values:
CustomerID         0
TransactionID      0
TransactionDate    0
Amount             0
ProductCategory    0
PaymentMethod      0
dtype: int64

Duplicate Rows:
0

In [53]:
# Import libraries for data preprocessing and analysis
import pandas as pd
import numpy as np

In [54]:
# Load the contaminated customer transactions dataset
transactions = pd.read_csv("customer_transactions_contaminated.csv")

In [55]:
# Inspect the first five rows of the dataset
transactions.head()

,CustomerID,TransactionID,TransactionDate,Amount,ProductCategory,PaymentMethod
0,60567026-f719-4cd6-849e-137e86d8938f,5ff75116-0a50-4d04-80fb-31e5ccbb0769,2024-05-15,117.64,Clothing,PayPal
1,4090ba85-b111-4f75-a792-c777965f5255,2c39b9fe-ff57-4d39-9321-9f5cdf187aa1,2023-04-26,466.14,Health & Beauty,Bank Transfer
2,9223891b-73ff-4d5c-b8ae-13ece82ee28b,f79588dd-3db9-4ffa-97f8-7de0e64259f1,2022-09-23,563.99,Clothing,Debit Card
3,9243eebc-938f-480c-8564-16d503d250de,401c0fc9-60df-4455-ad78-67c132f9897d,2024-04-15,254.44,Automotive,PayPal
4,6e3e8eb8-bc0f-4ffe-9f74-5d5efec9502f,2034aebc-8280-4254-a667-92bcd1c2be4f,2024-06-03,590.52,Home & Garden,Bank Transfer

In [56]:
# Check the number of rows and columns in the dataset
transactions.shape

(3200, 6)

In [57]:
# Review the data types of all columns
transactions.dtypes

CustomerID         str
TransactionID      str
TransactionDate    str
Amount             str
ProductCategory    str
PaymentMethod      str
dtype: object

In [58]:
# Identify the number of missing values in each column
transactions.isnull().sum()

CustomerID           0
TransactionID        0
TransactionDate      0
Amount             304
ProductCategory    299
PaymentMethod        0
dtype: int64

In [59]:
# Check the number of duplicate rows in the dataset
transactions.duplicated().sum()

np.int64(185)

In [60]:
# Remove duplicate rows and create a cleaned copy of the dataset
transactions_cleaned = transactions.drop_duplicates().copy()

In [61]:
# Check the dimensions after removing duplicate rows
transactions_cleaned.shape

(3015, 6)

In [62]:
# Inspect the most frequent values in the Amount column,
# including missing values
transactions_cleaned["Amount"].value_counts(dropna=False).head(20)

Amount
NaN       283
-100       39
Free       30
0          29
54.66       2
175.31      2
628.86      2
368.91      2
129.92      2
185.97      2
634.41      2
372.45      2
404.53      2
390.81      2
457.83      2
347.7       2
999.86      2
724.64      2
50.07       2
508.4       2
Name: count, dtype: int64

In [63]:
# Convert the Amount column to numeric values
# Invalid text values such as "Free" are converted to missing values
transactions_cleaned["Amount"] = pd.to_numeric(
    transactions_cleaned["Amount"],
    errors="coerce"
)

In [64]:
# Verify that the Amount column has been converted to a numeric data type
transactions_cleaned["Amount"].dtype

dtype('float64')

In [65]:
# Identify transaction records with negative Amount values
transactions_cleaned[transactions_cleaned["Amount"] < 0]

,CustomerID,TransactionID,TransactionDate,Amount,ProductCategory,PaymentMethod
274,e6f4ae74-d58d-4770-8ebc-89c1f8778a6d,814d25d8-690b-45bb-96c9-b7a3e92a61db,2023-01-25,-100.0,NaN,PayPal
319,b91999f9-b7ed-4da4-a285-1dafae98e21d,fb908e24-4c1e-4e24-a1b0-62465fa0515c,2024-03-22,-100.0,Health & Beauty,Debit Card
334,a800ccba-e1ca-4f52-ad9f-14f3432699c9,487ecd9b-57c8-447c-a2a8-e55477ba0d6d,2023-09-25,-100.0,Clothing,Bank Transfer
381,a94e3f55-2f0e-432e-8706-9815c4371376,f53b16b4-d042-44ca-a073-4acdd546b519,2024-01-06,-100.0,Home & Garden,PayPal
447,ca645b4d-28a4-42ec-99a7-8000d38bf2e0,f35cadbe-6ae1-427d-8b41-5749cc1173e6,2023-06-18,-100.0,Electronics,Bank Transfer
449,a7c29c33-e968-4d84-82cd-1269ed1e7c1e,77954a26-9a04-4806-b525-7f33f554d255,2022-09-11,-100.0,Home & Garden,Credit Card
476,ac6b4d61-3d14-4362-b226-8c0c5786d6df,1074d2cf-a7d5-4ebd-baa9-4660b2df5ec8,2023-07-17,-100.0,Health & Beauty,Credit Card
500,ffe9a403-ac25-4aad-a809-ac9687ff3fcd,c59819cc-cf92-4929-ad22-ef3435187be9,2023-04-01,-100.0,Automotive,Bank Transfer
563,f05ec030-ac96-417d-a73c-e3ca3adc1a30,f39c8b1d-595a-4656-8108-25981bf3fa14,03/04/2023,-100.0,Electronics,Debit Card
652,f56e56b7-bbde-455c-b570-61cd2005b4e4,f99eba1f-0092-4487-b753-9fce61e0ca26,2023-02-05,-100.0,Automotive,PayPal
702,ab87ecef-f7ea-49b0-8c50-c31442ad5c46,64138a25-3a63-41fd-aa81-f74231597191,2022-12-04,-100.0,Home & Garden,Debit Card
727,db10c135-1080-4fce-b653-d5a5fb572fa8,adbe44db-78ec-408b-80ad-e119e0f58123,2024-05-13,-100.0,Home & Garden,Credit Card
1129,6b6cd86a-d0af-48ab-ada5-e596f726cffa,eed1a5a0-4a6b-40b1-9c43-abfeff1a7735,2024-06-02,-100.0,Clothing,Credit Card
1240,03fac2e6-f130-4cf6-b8b8-2f147c2fe60a,6f57c9c3-0c11-4d34-9392-08eb6b91fd0e,2024-05-21,-100.0,Home & Garden,Debit Card
1241,799943c7-3b71-4f24-9b16-c2fcaf9b3871,09b0508b-a705-48d0-8594-5b7d85d024eb,2022-11-08,-100.0,Automotive,PayPal
1263,38d746bd-c227-416a-aa28-610ffd379e58,db154379-42a3-4ae0-a4d3-29c53226f8a1,2024-06-22,-100.0,Electronics,Bank Transfer
1298,8375d38f-88e2-4c33-9647-f8b8b55b1426,f01412a4-6d1c-46ce-a912-7b0a8c2a7596,2023-02-23,-100.0,Health & Beauty,Bank Transfer
1577,7eb7f7df-9b0a-416a-829e-bcf4d8bd57dc,6cfe5871-8524-4d81-abaa-a54fdd3c873d,2023-06-11,-100.0,Automotive,PayPal
1705,f102f93b-f32c-41d3-adcc-25e02a67c34f,084e56a5-99eb-48df-801e-bda9cd5ff591,2023-11-03,-100.0,Electronics,PayPal
1808,28097c07-e810-4e64-8eae-bff2abd81bc1,ab723d41-abdc-412b-b3b9-68796b746a8e,2023-07-11,-100.0,Automotive,Credit Card
1907,b7b84b81-c61b-4f23-b3db-b18010484122,d7740397-087b-49bb-bf31-2a50ca0e70f6,2023-03-14,-100.0,Clothing,PayPal
1942,e7e5e8fe-5fdd-43e6-92e1-5ea3e399486e,5b6352cf-da83-46ab-a0ff-79da90691392,2023-12-25,-100.0,Electronics,PayPal
1994,d968cee0-3524-42d4-a0f7-5fe6e8284890,0705d2f0-ab60-4664-b65e-971e3e2c27d5,2023-10-09,-100.0,Clothing,Debit Card
2191,1f5c50db-9c55-4bbc-8a93-c7994a7bb3d3,4b4ddbb6-36cf-44eb-8e7a-b27c529f1cff,2022-12-20,-100.0,Automotive,Bank Transfer
2239,448245da-3a0b-4f52-a40f-a25ca0a2fb6b,ddebc095-ed7c-4c6e-87d8-e7f00c0b50c6,2023-01-24,-100.0,Home & Garden,Credit Card
2319,21098ed8-fac6-4727-8f0c-953365b6c837,c100f59f-61aa-4c82-825e-dedfde73917b,2023-02-14,-100.0,Home & Garden,PayPal
2443,ce3f403f-b955-4364-ae22-bf351381e01f,0e5b9cc6-9b94-45fc-8bf8-b8031cd987a7,2023-04-21,-100.0,Home & Garden,Bank Transfer
2467,0e678ba1-7b5f-46aa-8b5a-6dc1190373be,33ce68ea-42c4-48eb-8631-c8f611d2a330,2023-03-01,-100.0,Clothing,Debit Card
2480,eca27290-1c40-48c6-b0a5-8afedd9be099,341e25ef-3062-484d-8d07-cc4e0ddb996f,2022-08-02,-100.0,Clothing,Credit Card
2516,7e280186-770e-4c4a-b330-73dd471f956a,35faff4a-1bf8-4b42-a7ac-847b4970f4b8,2023-09-19,-100.0,Home & Garden,Bank Transfer
2522,bfe55c3b-668e-485d-9476-670acd50b12b,52bb2a8d-acab-45f9-9817-6e9fe7567824,2024-05-03,-100.0,Health & Beauty,Debit Card
2621,8d435ee0-fa33-4553-880a-e26511ac3921,c0d0ae2b-eb99-49e5-89ad-0624ad136056,2023-03-27,-100.0,Home & Garden,Bank Transfer
2737,c56a1423-e1b0-45c1-974a-55f5fa029c88,b401a1e8-6cc3-4ab6-bff4-c41a3847329a,2024-05-31,-100.0,Electronics,PayPal
2910,f35c6e3f-2fac-4b7a-b713-863a0a37160c,e2d7a068-e92e-407a-8d48-4cf8da4a4c2c,2024-03-12,-100.0,Health & Beauty,PayPal
3012,24b043e8-6fca-4d86-95a8-837e0ca09072,dc9453eb-3922-4a5f-91c0-ccb226ca91f7,2023-06-01,-100.0,Health & Beauty,Debit Card
3038,b94b3531-591d-445c-b282-dcacb0baca5b,27fb25aa-f148-423f-967c-4d1764e26b29,2024-04-18,-100.0,Automotive,Credit Card
3050,a9af986b-d677-421a-81df-3d289ce9e38f,5f93f1dc-0363-4e69-979b-f5d58fd42658,2023-09-30,-100.0,NaN,Bank Transfer
3073,e7cf6999-b4ec-4ce4-bb09-bfd18d61d933,2e0b66a9-af5d-4cf9-bb60-55ab2932edee,2023-05-10,-100.0,Electronics,Bank Transfer
3123,8de3d5b9-1f1a-4bd7-b242-6cb09d7f3609,5fca256b-cd5a-48fa-8b07-37f39adde8c9,2023-05-17,-100.0,Clothing,Bank Transfer
3177,3ea377e6-1156-457e-8b4e-71fa6663e6bf,c751a808-ed8d-44d0-8c52-8253ad564c9a,2023-09-22,-100.0,Health & Beauty,Credit Card

In [66]:
# Replace invalid negative transaction amounts with missing values
transactions_cleaned.loc[
    transactions_cleaned["Amount"] < 0,
    "Amount"
] = np.nan

In [67]:
# Count the remaining missing values in the Amount column
transactions_cleaned["Amount"].isnull().sum()

np.int64(353)

In [68]:
# Calculate the median of the valid transaction amounts
transactions_cleaned["Amount"].median()

np.float64(504.14)

In [69]:
# Replace missing and invalid Amount values with the median value
transactions_cleaned["Amount"] = transactions_cleaned["Amount"].fillna(504.14)

In [70]:
# Verify that no missing values remain in the Amount column
transactions_cleaned["Amount"].isnull().sum()

np.int64(0)

In [71]:
# Inspect product categories and identify missing category values
transactions_cleaned["ProductCategory"].value_counts(dropna=False)

ProductCategory
Clothing           571
Electronics        564
Automotive         540
Home & Garden      530
Health & Beauty    528
NaN                282
Name: count, dtype: int64

In [72]:
# Replace missing product categories with "Unknown"
transactions_cleaned["ProductCategory"] = transactions_cleaned["ProductCategory"].fillna("Unknown")

In [73]:
# Verify that no missing values remain in ProductCategory
transactions_cleaned["ProductCategory"].isnull().sum()

np.int64(0)

In [74]:
# Inspect the most common transaction dates
transactions_cleaned["TransactionDate"].value_counts().head(10)

TransactionDate
2022-10-31    11
2024-01-06    11
2023-05-28    10
2022-12-14    10
2023-04-06    10
2023-10-19    10
2023-05-17    10
2023-12-19    10
2022-09-23     9
2024-01-12     9
Name: count, dtype: int64

In [75]:
# Identify transaction dates that use the DD/MM/YYYY format
transactions_cleaned[
    transactions_cleaned["TransactionDate"].str.contains("/", na=False)
]["TransactionDate"].value_counts().head(20)

TransactionDate
30/05/2023    3
24/05/2023    2
12/06/2024    2
17/10/2023    2
27/03/2024    2
01/04/2024    1
13/12/2022    1
26/10/2022    1
25/02/2023    1
23/03/2023    1
16/09/2023    1
11/09/2023    1
28/10/2022    1
12/10/2023    1
13/04/2023    1
30/07/2022    1
29/12/2023    1
04/03/2023    1
06/07/2022    1
12/07/2023    1
Name: count, dtype: int64

In [76]:
# Convert mixed date formats into a consistent datetime format
transactions_cleaned["TransactionDate"] = pd.to_datetime(
    transactions_cleaned["TransactionDate"],
    format="mixed",
    dayfirst=True,
    errors="coerce"
)

In [77]:
# Verify that TransactionDate is stored as a datetime data type
transactions_cleaned["TransactionDate"].dtype

dtype('<M8[us]')

In [78]:
# Check whether any transaction dates became missing after conversion
transactions_cleaned["TransactionDate"].isnull().sum()

np.int64(0)

In [79]:
# Perform a final quality check on the cleaned dataset

print("FINAL DATASET CHECK")
print("-------------------")

print("\nDataset Shape:")
print(transactions_cleaned.shape)

print("\nData Types:")
print(transactions_cleaned.dtypes)

print("\nMissing Values:")
print(transactions_cleaned.isnull().sum())

print("\nDuplicate Rows:")
print(transactions_cleaned.duplicated().sum())

FINAL DATASET CHECK
-------------------

Dataset Shape:
(3015, 6)

Data Types:
CustomerID                    str
TransactionID                 str
TransactionDate    datetime64[us]
Amount                    float64
ProductCategory               str
PaymentMethod                 str
dtype: object

Missing Values:
CustomerID         0
TransactionID      0
TransactionDate    0
Amount             0
ProductCategory    0
PaymentMethod      0
dtype: int64

Duplicate Rows:
0

In [80]:
# Save the finalized preprocessed dataset as a new CSV file
# The original contaminated dataset remains unchanged
transactions_cleaned.to_csv(
    "customer_transactions_preprocessed.csv",
    index=False
)

print("Preprocessed dataset saved successfully!")

Preprocessed dataset saved successfully!